<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-15">
<meta name="description" content="Comparing three polynomial staking-offset shapes — linear, smoothstep (3u²−2u³), and quadratic (2u−u²) — each calibrated to match current issuance at 33% staked. Smoothstep reaches zero at 50% with the gentlest slope of the three; the quadratic curve provides the strongest incentive for low-staking scenarios but at the cost of a much larger BASE_REWARD_FACTOR.">

<title>Smooth Issuance Tapering: Polynomial Offsets for Ethereum – pintail’s notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-2cb179d66e5887d6bd257c4a22d491ba.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script data-goatcounter="https://pintail.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<meta name="quarto:status" content="draft">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Smooth Issuance Tapering: Polynomial Offsets for Ethereum – pintail’s notes">
<meta property="og:description" content="Comparing three polynomial staking-offset shapes — linear, smoothstep (3u²−2u³), and quadratic (2u−u²) — each calibrated to match current issuance at 33% staked. Smoothstep reaches zero at 50% with the gentlest slope of the three; the quadratic curve provides the strongest incentive for low-staking scenarios but at the cost of a much larger BASE_REWARD_FACTOR.">
<meta property="og:site_name" content="pintail's notes">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><div id="quarto-draft-alert" class="alert alert-warning"><i class="bi bi-pencil-square"></i>Draft</div>
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../assets/pintail_silhouette.svg" alt="Pintail duck silhouette" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">pintail’s notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/pintail_xyz"> <i class="bi bi-twitter" role="img" aria-label="Twitter">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/pintail-xyz"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tldr" id="toc-tldr" class="nav-link active" data-scroll-target="#tldr">tl;dr</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#calibration" id="toc-calibration" class="nav-link" data-scroll-target="#calibration">Calibration</a></li>
  <li><a href="#properties" id="toc-properties" class="nav-link" data-scroll-target="#properties">Properties</a>
  <ul class="collapse">
  <li><a href="#yield" id="toc-yield" class="nav-link" data-scroll-target="#yield">Yield</a></li>
  <li><a href="#slope-at-saturation" id="toc-slope-at-saturation" class="nav-link" data-scroll-target="#slope-at-saturation">Slope at saturation</a></li>
  <li><a href="#total-issuance" id="toc-total-issuance" class="nav-link" data-scroll-target="#total-issuance">Total Issuance</a></li>
  </ul></li>
  <li><a href="#spec-considerations" id="toc-spec-considerations" class="nav-link" data-scroll-target="#spec-considerations">Spec Considerations</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Smooth Issuance Tapering: Polynomial Offsets for Ethereum</h1>
</div>

<div>
  <div class="description">
    Comparing three polynomial staking-offset shapes — linear, smoothstep (3u²−2u³), and quadratic (2u−u²) — each calibrated to match current issuance at 33% staked. Smoothstep reaches zero at 50% with the gentlest slope of the three; the quadratic curve provides the strongest incentive for low-staking scenarios but at the cost of a much larger BASE_REWARD_FACTOR.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>The <a href="../linear-issuance-tapering/">linear staking offset</a> is a clean, implementable design: subtract a per-validator penalty proportional to the current staking ratio so that net issuance falls smoothly to zero at 50% staked. Its one notable shortcoming is that it approaches the zero-issuance point at a constant rate — the yield curve has a non-zero slope right up to the saturation point, making it a relatively sharp final approach.</p>
<p>This post explores two polynomial alternatives that share the same structural simplicity but reach zero more gently.</p>
<section id="tldr" class="level2">
<h2 class="anchored" data-anchor-id="tldr">tl;dr</h2>
<ul>
<li>Three polynomial offset shapes — <strong>linear</strong> (<span class="math inline">\(u\)</span>), <strong>smoothstep</strong> (<span class="math inline">\(3u^2-2u^3\)</span>), and <strong>quadratic</strong> (<span class="math inline">\(2u-u^2\)</span>) — all satisfy <span class="math inline">\(\phi(0)=0\)</span> and <span class="math inline">\(\phi(1)=1\)</span>, so all three pin net issuance to zero at 50% staked.</li>
<li>Calibrating each curve so that net yield matches current issuance at <span class="math inline">\(f \approx 33\%\)</span> determines the required <code>BASE_REWARD_FACTOR</code> (<span class="math inline">\(B\)</span>): approximately 140, 162, and 233 for linear, smoothstep, and quadratic respectively.</li>
<li>Smoothstep and quadratic both have zero slope at <span class="math inline">\(u=1\)</span>, giving a softer final approach to zero; smoothstep also has zero slope at <span class="math inline">\(u=0\)</span>. In absolute terms, smoothstep reaches saturation at 38% of the linear slope, and quadratic at 55%.</li>
<li>Below 33% staked, the quadratic offset provides the highest yields (strongest stabiliser); above 33% it tapers more aggressively than smoothstep. Linear is the most conservative throughout.</li>
<li>The large calibrated <span class="math inline">\(B \approx 233\)</span> for the quadratic option implies that all consensus-layer penalties scale up by a factor of <span class="math inline">\(\sim\!3.6\times\)</span> relative to today — a significant governance consideration.</li>
</ul>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>Let <span class="math inline">\(r(f) = B \cdot E / \sqrt{f \cdot S \cdot 10^9}\)</span> be the gross nominal yield at staking ratio <span class="math inline">\(f\)</span>, computed with <code>BASE_REWARD_FACTOR</code> <span class="math inline">\(= B\)</span> and epochs-per-year <span class="math inline">\(E\)</span>. Write <span class="math inline">\(r_\text{sat} = r(f_\text{sat})\)</span> for the gross yield at the saturation point <span class="math inline">\(f_\text{sat} = 50\%\)</span>. The net yield under each proposal is:</p>
<p><span class="math display">\[r_\text{new}(f) = \begin{cases} K\,\bigl[r_{64}(f) - \phi(f/f_\text{sat})\cdot r_{64}(f_\text{sat})\bigr] &amp; f \le f_\text{sat} \\ 0 &amp; f &gt; f_\text{sat} \end{cases}\]</span></p>
<p>where <span class="math inline">\(r_{64}\)</span> denotes the yield with the current <code>BASE_REWARD_FACTOR</code> <span class="math inline">\(= 64\)</span> and <span class="math inline">\(K = B/64\)</span> is the gross reward multiplier. Above <span class="math inline">\(f_\text{sat}\)</span> the offset equals the full base reward and net yield is zero.</p>
<p>The three offset shapes, defined on <span class="math inline">\(u = f/f_\text{sat} \in [0,1]\)</span>, are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variant</th>
<th><span class="math inline">\(\phi(u)\)</span></th>
<th><span class="math inline">\(\phi'(0)\)</span></th>
<th><span class="math inline">\(\phi'(1)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linear</td>
<td><span class="math inline">\(u\)</span></td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Smoothstep</td>
<td><span class="math inline">\(3u^2 - 2u^3\)</span></td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Quadratic</td>
<td><span class="math inline">\(2u - u^2\)</span></td>
<td>2</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>All three satisfy <span class="math inline">\(\phi(0) = 0\)</span> and <span class="math inline">\(\phi(1) = 1\)</span>, so all reach exactly zero net yield at 50% staked. Because each is a polynomial in <span class="math inline">\(u\)</span>, it extends naturally above <span class="math inline">\(u = 1\)</span> without pathological behaviour (unlike sine-based shapes), so no clamping is needed — all three are strictly above 1 for <span class="math inline">\(u &gt; 1\)</span>, keeping net yield at zero above saturation.</p>
<div id="fig-offset" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-offset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<style>
  #poly-offsetcurve-chart { width: 100%; height: 460px; }
</style>

<div id="poly-offsetcurve-chart"></div>

<script src="offsetcurve.js"></script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-offset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The three offset shapes <span class="math inline">\(\phi(u)\)</span> as a fraction of the base reward. Linear rises at a constant rate. Smoothstep (an interpolating polynomial widely used in computer graphics) starts and ends with zero slope — it is sigmoidal, lying below the linear line for <span class="math inline">\(u &lt; \tfrac{1}{2}\)</span> and above it for <span class="math inline">\(u &gt; \tfrac{1}{2}\)</span>. Quadratic (<span class="math inline">\(2u - u^2\)</span>) lies above the linear line everywhere and has zero slope at <span class="math inline">\(u = 1\)</span>; it is the mirror image of a downward-opening parabola.
</figcaption>
</figure>
</div>
</section>
<section id="calibration" class="level2">
<h2 class="anchored" data-anchor-id="calibration">Calibration</h2>
<p>To isolate the effect of shape from the effect of level, we calibrate <span class="math inline">\(K\)</span> for each variant so that net yield at the current staking ratio <span class="math inline">\(f_0 = \tfrac{1}{3}\)</span> equals today’s yield:</p>
<p><span class="math display">\[K \cdot \Bigl[r_{64}(f_0) - \phi\!\bigl(f_0/f_\text{sat}\bigr)\cdot r_{64}(f_\text{sat})\Bigr] = r_{64}(f_0)\]</span></p>
<p>Since <span class="math inline">\(r_{64}(f_\text{sat})/r_{64}(f_0) = \sqrt{f_0/f_\text{sat}} = \sqrt{2/3}\)</span> and <span class="math inline">\(u_0 = f_0/f_\text{sat} = \tfrac{2}{3}\)</span>:</p>
<p><span class="math display">\[K = \frac{1}{1 - \phi(2/3)\cdot\sqrt{2/3}}\]</span></p>
<p>The three calibrated values are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Variant</th>
<th><span class="math inline">\(\phi(2/3)\)</span></th>
<th><span class="math inline">\(\phi(2/3)\cdot\sqrt{2/3}\)</span></th>
<th><span class="math inline">\(K\)</span></th>
<th><span class="math inline">\(B = 64K\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linear</td>
<td><span class="math inline">\(2/3\)</span></td>
<td><span class="math inline">\(2\sqrt{6}/9 \approx 0.544\)</span></td>
<td><span class="math inline">\(9/(9-2\sqrt{6}) \approx 2.195\)</span></td>
<td><span class="math inline">\(\approx 140\)</span></td>
</tr>
<tr class="even">
<td>Smoothstep</td>
<td><span class="math inline">\(20/27\)</span></td>
<td><span class="math inline">\(20\sqrt{6}/81 \approx 0.605\)</span></td>
<td><span class="math inline">\(81/(81-20\sqrt{6}) \approx 2.530\)</span></td>
<td><span class="math inline">\(\approx 162\)</span></td>
</tr>
<tr class="odd">
<td>Quadratic</td>
<td><span class="math inline">\(8/9\)</span></td>
<td><span class="math inline">\(8\sqrt{6}/27 \approx 0.726\)</span></td>
<td><span class="math inline">\(27/(27-8\sqrt{6}) \approx 3.647\)</span></td>
<td><span class="math inline">\(\approx 233\)</span></td>
</tr>
</tbody>
</table>
<p>All three exact expressions involve <span class="math inline">\(\sqrt{6}\)</span> because <span class="math inline">\(\sqrt{2/3} \cdot (2/3)^n\)</span> simplifies to a rational multiple of <span class="math inline">\(\sqrt{6}\)</span> for integer <span class="math inline">\(n\)</span>. None of the <span class="math inline">\(B\)</span> values are round integers — see <a href="#spec-considerations">spec considerations</a> below.</p>
</section>
<section id="properties" class="level2">
<h2 class="anchored" data-anchor-id="properties">Properties</h2>
<section id="yield" class="level3">
<h3 class="anchored" data-anchor-id="yield">Yield</h3>
<div id="fig-yield" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yield-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<style>
  #poly-yieldcurve-chart { width: 100%; height: 460px; }
</style>

<div id="poly-yieldcurve-chart"></div>

<script src="yieldcurve.js"></script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yield-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Consensus-layer nominal yield as a function of staking ratio. All three proposed curves pass through the same point as the current curve at <span class="math inline">\(f = 33\%\)</span>. Below 33%, all three offer higher yields than today; the quadratic variant is the most generous at low staking. Above 33%, smoothstep and quadratic taper more aggressively than the linear variant. All three reach zero at 50%.
</figcaption>
</figure>
</div>
<p><strong>Below 33%</strong> — all three proposed curves lie above today’s yield, since <span class="math inline">\(K &gt; 1\)</span> in every case. The quadratic variant, with the largest <span class="math inline">\(K \approx 3.65\)</span>, provides the strongest stabilising incentive when staking is low: at 10% staking, it offers roughly five times today’s yield. The smoothstep and linear variants are progressively more conservative.</p>
<p><strong>Above 33%</strong> — smoothstep and quadratic both taper faster than the linear variant. By 40% staking the linear variant still offers roughly 57% of today’s yield; smoothstep and quadratic are both closer to 40–45%. By 45%, linear is at about 28% of today’s yield while smoothstep and quadratic are both below 20%. The two smooth variants provide a stronger automatic market signal against excess staking throughout the danger zone.</p>
<p>Note that despite both having <span class="math inline">\(\phi'(1) = 0\)</span>, smoothstep and quadratic behave differently in the 33–50% range: smoothstep lies closer to the linear curve (it is sigmoidal and still rising steeply in the upper half), while the quadratic offset is larger throughout, causing more aggressive tapering above 33%.</p>
</section>
<section id="slope-at-saturation" class="level3">
<h3 class="anchored" data-anchor-id="slope-at-saturation">Slope at saturation</h3>
<p>The key qualitative difference among the variants is how abruptly net yield falls to zero at <span class="math inline">\(f = f_\text{sat}\)</span>. Computing <span class="math inline">\(dr_\text{new}/df\)</span> from below at <span class="math inline">\(f = f_\text{sat}\)</span>, using <span class="math inline">\(dr/df|_{f_\text{sat}} = -r_\text{sat}/(2f_\text{sat})\)</span>:</p>
<p><span class="math display">\[\left.\frac{dr_\text{new}}{df}\right|_{f=f_\text{sat}^-} = -\frac{K\,r_\text{sat}}{f_\text{sat}}\left(\frac{1}{2} + \phi'(1)\right)\]</span></p>
<p>Since <span class="math inline">\(\phi'(1) = 1\)</span> for linear and <span class="math inline">\(\phi'(1) = 0\)</span> for both smooth curves, the slope at saturation is three times larger (in magnitude) for the linear variant than it would be if <span class="math inline">\(K\)</span> were the same. But <span class="math inline">\(K\)</span> differs across variants too, so the absolute slope ratios are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variant</th>
<th>Slope factor <span class="math inline">\(K(\tfrac{1}{2}+\phi'(1))\)</span></th>
<th>Relative to linear</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linear</td>
<td><span class="math inline">\(2.195 \times 1.5 = 3.29\)</span></td>
<td>1.00</td>
</tr>
<tr class="even">
<td>Smoothstep</td>
<td><span class="math inline">\(2.530 \times 0.5 = 1.27\)</span></td>
<td>0.38</td>
</tr>
<tr class="odd">
<td>Quadratic</td>
<td><span class="math inline">\(3.647 \times 0.5 = 1.82\)</span></td>
<td>0.55</td>
</tr>
</tbody>
</table>
<p>Smoothstep reaches zero with only 38% of the linear slope — the softest landing. Quadratic, despite its larger <span class="math inline">\(K\)</span>, still lands at 55% of the linear slope because <span class="math inline">\(\phi'(1) = 0\)</span> halves the effective slope factor.</p>
</section>
<section id="total-issuance" class="level3">
<h3 class="anchored" data-anchor-id="total-issuance">Total Issuance</h3>
<div id="fig-issuance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-issuance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<style>
  #poly-issuancecurve-chart { width: 100%; height: 460px; }
</style>

<div id="poly-issuancecurve-chart"></div>

<script src="issuancecurve.js"></script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-issuance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Annual ETH issuance as a percentage of total supply. All three proposed curves equal the current issuance at <span class="math inline">\(f = 33\%\)</span> and fall to zero at <span class="math inline">\(f = 50\%\)</span>. The proposed curves each peak at a lower staking ratio than the current curve.
</figcaption>
</figure>
</div>
<p>The annual issuance is <span class="math inline">\(I(f) = r_\text{new}(f) \cdot f \cdot S\)</span>, which peaks at some <span class="math inline">\(f^* &lt; f_\text{sat}\)</span>. Below <span class="math inline">\(f^*\)</span>, total issuance is increasing — higher staking draws more ETH into circulation. Above <span class="math inline">\(f^*\)</span>, additional staking actually reduces total issuance, providing an extra systemic pull back toward equilibrium.</p>
<p>The peak location <span class="math inline">\(f^*\)</span> depends only on the offset shape <span class="math inline">\(\phi\)</span>, not on <span class="math inline">\(K\)</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variant</th>
<th><span class="math inline">\(f^*\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linear</td>
<td><span class="math inline">\(\approx 19.8\%\)</span></td>
</tr>
<tr class="even">
<td>Smoothstep</td>
<td><span class="math inline">\(\approx 18.4\%\)</span></td>
</tr>
<tr class="odd">
<td>Quadratic</td>
<td><span class="math inline">\(\approx 14.8\%\)</span></td>
</tr>
</tbody>
</table>
<p>All three lie well below the current <span class="math inline">\(\sim\!33\%\)</span> staking ratio, so the anti-discouragement property holds in every case: at current staking levels, the equilibrium is already on the downward slope of the issuance curve, meaning the protocol is already automatically discouraging further staking growth.</p>
</section>
</section>
<section id="spec-considerations" class="level2">
<h2 class="anchored" data-anchor-id="spec-considerations">Spec Considerations</h2>
<p>All three offset shapes are simple polynomial expressions — one subtract and two multiplies for the smoothstep, one subtract and one multiply for the quadratic — and can be evaluated exactly in integer arithmetic with a small fixed-point representation. This is a practical advantage over transcendental functions (sine, cosine) which require approximation.</p>
<p>The calibrated <code>BASE_REWARD_FACTOR</code> values (≈ 140, 162, 233) are not round integers. In practice the spec would choose the nearest integer. Rounding from 161.9 to 162 for smoothstep, or from 233.4 to 233 for quadratic, introduces a deviation of less than 0.3% at the 33% calibration point — well within the precision of any practical implementation.</p>
<p>The <a href="../linear-issuance-tapering/">original linear proposal</a> used <span class="math inline">\(B = 128\)</span> (<span class="math inline">\(K = 2\)</span>) as a convenient round value, deliberately accepting a small yield reduction at deployment rather than requiring an exact match.</p>
<p><strong>Penalty scaling.</strong> All consensus-layer penalties — inactivity leaks and slashing — scale linearly with <code>BASE_REWARD_FACTOR</code>. The calibrated <span class="math inline">\(B\)</span> values imply penalty increases relative to today of:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variant</th>
<th><span class="math inline">\(B\)</span></th>
<th>Penalty multiplier</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Current</td>
<td>64</td>
<td><span class="math inline">\(1.0\times\)</span></td>
</tr>
<tr class="even">
<td>Linear</td>
<td>≈ 140</td>
<td><span class="math inline">\(\approx 2.2\times\)</span></td>
</tr>
<tr class="odd">
<td>Smoothstep</td>
<td>≈ 162</td>
<td><span class="math inline">\(\approx 2.5\times\)</span></td>
</tr>
<tr class="even">
<td>Quadratic</td>
<td>≈ 233</td>
<td><span class="math inline">\(\approx 3.6\times\)</span></td>
</tr>
</tbody>
</table>
<p>The quadratic option’s large <span class="math inline">\(K\)</span> means validators face substantially higher inactivity and slashing penalties — a significant governance consideration that is independent of the yield question.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>Calibrated at 33%, the three polynomial shapes separate cleanly into two regime differences:</p>
<ol type="1">
<li><p><strong>Below 33%</strong>: how generously they reward stakers when participation is low. Quadratic is the most generous (largest K); linear the most conservative. All are above the current curve and all provide a stronger stabilising pull than today’s issuance schedule.</p></li>
<li><p><strong>Above 33%</strong>: how aggressively they taper against excess staking, and how smoothly they approach zero at 50%. Both smooth curves taper faster than linear; smoothstep is slightly gentler than quadratic in the 33–45% range. Both reach zero more gradually than linear.</p></li>
</ol>
<p>The smoothstep polynomial occupies the middle ground in almost every respect: more aggressive than linear above 33% (providing a stronger discouraging signal), softer than linear at saturation (no abrupt cliff), and with a more moderate penalty multiplier than the quadratic. Its S-shaped curve — familiar from computer graphics and signal processing — has the additional intuitive property that the offset <em>accelerates</em> through the middle of the range and then <em>decelerates</em> as it approaches saturation.</p>
<p>The quadratic option is distinguished primarily by its behaviour at low staking: its concave shape means the offset rises quickly at first and then flattens, leaving a larger gross reward at low <span class="math inline">\(f\)</span>. This makes it the strongest automatic stabiliser if staking collapses but requires accepting substantially larger penalties as the cost of calibration.</p>
<p>The linear offset remains the most practically deployable: <span class="math inline">\(B = 128\)</span> is a clean integer, it reduces to a single multiply-and-divide in the spec, and the penalty increase is the most modest. Whether the softer landing and stronger corrective properties of smoothstep justify the additional complexity (<span class="math inline">\(B \approx 162\)</span>, a non-integer) is a judgment call for the community.</p>
<p>For comparison with transcendental alternatives (sine and S-curve offsets), see the companion post <a href="../sine-issuance-tapering/">Smooth Issuance Tapering: Sine and S-Curve Offsets</a>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/pintail\.xyz");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="pintail-xyz/pintail-xyz.github.io" data-repo-id="MDEwOlJlcG9zaXRvcnkzMDUwNjk1MTY=" data-category="General" data-category-id="DIC_kwDOEi79zM4C47Ma" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© Pintail</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>