<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-17">
<meta name="description" content="Both proposals apply a linear offset to bring Ethereum consensus-layer issuance to zero at 50% staked. The difference is whether the base reward formula itself is also modified. Despite sharing the same calibration point and the same zero at saturation, the yield curves take genuinely different shapes.">

<title>Offset vs.&nbsp;Blend-and-Offset: Comparing Two Linear Tapering Approaches – pintail's notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-2cb179d66e5887d6bd257c4a22d491ba.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script data-goatcounter="https://pintail.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<meta name="quarto:status" content="draft">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Offset vs.&nbsp;Blend-and-Offset: Comparing Two Linear Tapering Approaches – pintail’s notes">
<meta property="og:description" content="Both proposals apply a linear offset to bring Ethereum consensus-layer issuance to zero at 50% staked. The difference is whether the base reward formula itself is also modified. Despite sharing the same calibration point and the same zero at saturation, the yield curves take genuinely different shapes.">
<meta property="og:site_name" content="pintail's notes">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><div id="quarto-draft-alert" class="alert alert-warning"><i class="bi bi-pencil-square"></i>Draft</div>
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../assets/pintail_silhouette.svg" alt="Pintail duck silhouette" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">pintail’s notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../drafts.html"> 
<span class="menu-text">Drafts</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/pintail_xyz"> <i class="bi bi-twitter" role="img" aria-label="Twitter">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/pintail-xyz"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-two-formulas" id="toc-the-two-formulas" class="nav-link active" data-scroll-target="#the-two-formulas">The two formulas</a>
  <ul class="collapse">
  <li><a href="#approach-a-offset-only" id="toc-approach-a-offset-only" class="nav-link" data-scroll-target="#approach-a-offset-only">Approach A — offset only</a></li>
  <li><a href="#approach-b-linear-blend-of-base-reward-then-offset" id="toc-approach-b-linear-blend-of-base-reward-then-offset" class="nav-link" data-scroll-target="#approach-b-linear-blend-of-base-reward-then-offset">Approach B — linear blend of base reward, then offset</a></li>
  <li><a href="#calibration" id="toc-calibration" class="nav-link" data-scroll-target="#calibration">Calibration</a></li>
  </ul></li>
  <li><a href="#do-the-yield-curves-differ" id="toc-do-the-yield-curves-differ" class="nav-link" data-scroll-target="#do-the-yield-curves-differ">Do the yield curves differ?</a></li>
  <li><a href="#total-issuance" id="toc-total-issuance" class="nav-link" data-scroll-target="#total-issuance">Total issuance</a></li>
  <li><a href="#properties-compared" id="toc-properties-compared" class="nav-link" data-scroll-target="#properties-compared">Properties compared</a>
  <ul class="collapse">
  <li><a href="#slope-at-saturation" id="toc-slope-at-saturation" class="nav-link" data-scroll-target="#slope-at-saturation">Slope at saturation</a></li>
  <li><a href="#penalty-implications" id="toc-penalty-implications" class="nav-link" data-scroll-target="#penalty-implications">Penalty implications</a></li>
  <li><a href="#spec-architecture" id="toc-spec-architecture" class="nav-link" data-scroll-target="#spec-architecture">Spec architecture</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Offset vs.&nbsp;Blend-and-Offset: Comparing Two Linear Tapering Approaches</h1>
</div>

<div>
  <div class="description">
    Both proposals apply a linear offset to bring Ethereum consensus-layer issuance to zero at 50% staked. The difference is whether the base reward formula itself is also modified. Despite sharing the same calibration point and the same zero at saturation, the yield curves take genuinely different shapes.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 17, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Two approaches to linear issuance tapering have been explored in earlier posts. The <a href="../linear-issuance-tapering/">simpler one</a> leaves <code>get_base_reward_per_increment</code> — the <span class="math inline">\(1/\sqrt{f}\)</span> formula — untouched and adds a separate linear offset that cancels net issuance at 50% staked. The <a href="../linear-taper/">more structured one</a> first modifies the base reward formula to blend linearly from the <span class="math inline">\(1/\sqrt{f}\)</span> curve at low staking to a flat level at saturation, and then applies a matching linear offset on top. In both cases, calibrating <code>BASE_REWARD_FACTOR</code> to reproduce today’s consensus-layer yield at <span class="math inline">\(\sim\!33\%\)</span> staked makes them directly comparable.</p>
<p>The question this post answers: with matched calibration, do the net yield curves actually differ?</p>
<section id="the-two-formulas" class="level2">
<h2 class="anchored" data-anchor-id="the-two-formulas">The two formulas</h2>
<p>Let <span class="math inline">\(r_{64}(f) = B_0 E / \sqrt{f \cdot S \cdot 10^9}\)</span> be the current consensus-layer yield at staking ratio <span class="math inline">\(f\)</span> (<span class="math inline">\(B_0 = 64\)</span>), and write <span class="math inline">\(u = f/f_\text{sat}\)</span> for the normalised staking level (<span class="math inline">\(f_\text{sat} = 50\%\)</span>, <span class="math inline">\(r_\text{sat} = r_{64}(f_\text{sat}) \approx 2.14\%\)</span>).</p>
<section id="approach-a-offset-only" class="level3">
<h3 class="anchored" data-anchor-id="approach-a-offset-only">Approach A — offset only</h3>
<p>The base reward formula is unchanged; <code>BASE_REWARD_FACTOR</code> is raised from 64 to <span class="math inline">\(K_A \times 64\)</span>. A new function <code>get_base_reward_offset_per_increment</code> returns a per-epoch deduction that grows linearly with total staking from zero to the gross base reward at saturation:</p>
<p><span class="math display">\[\text{offset}(f) = K_A \cdot u \cdot r_\text{sat}\]</span></p>
<p>The net yield is:</p>
<p><span class="math display">\[r_A(f) = K_A \cdot \max\!\bigl(0,\; r_{64}(f) - u\,r_\text{sat}\bigr)\]</span></p>
<p>Using <span class="math inline">\(r_\text{sat}/r_{64}(f) = u^{1/2}\)</span> (since <span class="math inline">\(r_{64}(f) \propto f^{-1/2}\)</span>), this simplifies to:</p>
<p><span class="math display">\[\boxed{r_A(f) = K_A\,r_{64}(f)\cdot\max\!\bigl(0,\; 1 - u^{3/2}\bigr)}\]</span></p>
<p>The factor <span class="math inline">\(u^{3/2}\)</span> appears because <span class="math inline">\(r_{64}(f) \propto u^{-1/2}\)</span> — the offset is proportional to <span class="math inline">\(u\)</span> but the gross yield is proportional to <span class="math inline">\(u^{-1/2}\)</span>, so their ratio is <span class="math inline">\(u^{3/2}\)</span>.</p>
</section>
<section id="approach-b-linear-blend-of-base-reward-then-offset" class="level3">
<h3 class="anchored" data-anchor-id="approach-b-linear-blend-of-base-reward-then-offset">Approach B — linear blend of base reward, then offset</h3>
<p><code>get_base_reward_per_increment</code> is modified to blend linearly between the <span class="math inline">\(K_B\)</span>-scaled current formula and the flat level <span class="math inline">\(r_\text{sat}\)</span> (the value the <strong>original</strong> <span class="math inline">\(B_0 = 64\)</span> formula gives at saturation):</p>
<p><span class="math display">\[\tilde{r}(f) = (1-u)\,K_B\,r_{64}(f) + u\,r_\text{sat}, \qquad f \le f_\text{sat}; \quad r_\text{sat} \text{ above}\]</span></p>
<p>A separate offset function then adds the same linear deduction:</p>
<p><span class="math display">\[\text{offset}(f) = u \cdot r_\text{sat}\]</span></p>
<p>Subtracting, the <span class="math inline">\(r_\text{sat}\)</span> terms cancel exactly:</p>
<p><span class="math display">\[\tilde{r}(f) - \text{offset}(f) = (1-u)\,K_B\,r_{64}(f) + \cancel{u\,r_\text{sat}} - \cancel{u\,r_\text{sat}}\]</span></p>
<p><span class="math display">\[\boxed{r_B(f) = K_B\,(1-u)\,r_{64}(f)}\]</span></p>
<p>The blend was needed to construct the gross yield and to motivate the offset shape, but the net formula is simply the existing <span class="math inline">\(r_{64}\)</span> scaled down by the linear weight <span class="math inline">\((1-u)\)</span>.</p>
</section>
<section id="calibration" class="level3">
<h3 class="anchored" data-anchor-id="calibration">Calibration</h3>
<p>Both proposals are calibrated so the net yield at the current staking ratio <span class="math inline">\(f_0 \approx \tfrac{1}{3}\)</span> (<span class="math inline">\(u_0 = \tfrac{2}{3}\)</span>) equals today’s consensus-layer yield <span class="math inline">\(r_{64}(f_0)\)</span>.</p>
<p><strong>Approach A:</strong> <span class="math inline">\(K_A \cdot r_{64}(f_0) \cdot (1 - u_0^{3/2}) = r_{64}(f_0)\)</span>, giving:</p>
<p><span class="math display">\[K_A = \frac{1}{1 - u_0^{3/2}} = \frac{1}{1-(2/3)^{3/2}} \approx 2.195 \implies B_A \approx 140\]</span></p>
<p><strong>Approach B:</strong> <span class="math inline">\(K_B \cdot (1 - u_0) \cdot r_{64}(f_0) = r_{64}(f_0)\)</span>, giving:</p>
<p><span class="math display">\[K_B = \frac{1}{1-u_0} = \frac{1}{1 - 2/3} = 3 \implies B_B = 192\]</span></p>
<p>Both <span class="math inline">\(B_A \approx 140\)</span> and <span class="math inline">\(B_B = 192\)</span> are close multiples of <span class="math inline">\(B_0 = 64\)</span>, but only <span class="math inline">\(B_B\)</span> is an exact integer multiple (<span class="math inline">\(3 \times 64\)</span>).</p>
</section>
</section>
<section id="do-the-yield-curves-differ" class="level2">
<h2 class="anchored" data-anchor-id="do-the-yield-curves-differ">Do the yield curves differ?</h2>
<p>Yes. The net taper functions — the multipliers applied to <span class="math inline">\(r_{64}(f)\)</span> — are:</p>
<p><span class="math display">\[\text{A:}\quad K_A\bigl(1 - u^{3/2}\bigr) \qquad \text{B:}\quad K_B\,(1-u)\]</span></p>
<p>Both vanish at <span class="math inline">\(u = 1\)</span> and both equal 1 at <span class="math inline">\(u_0 = 2/3\)</span> by construction. But <span class="math inline">\(u^{3/2}\)</span> and <span class="math inline">\(u\)</span> are different functions of <span class="math inline">\(u\)</span>, so the curves disagree at every other staking ratio.</p>
<div id="fig-yield" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yield-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<style>
  #comparison-yieldcurve-chart { width: 100%; height: 460px; }
</style>

<div id="comparison-yieldcurve-chart"></div>

<script src="yieldcurve.js"></script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yield-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Consensus-layer nominal yield for the current curve (blue), the offset-only proposal (purple, <span class="math inline">\(B \approx 140\)</span>), and the blend-and-offset proposal (teal, <span class="math inline">\(B = 192\)</span>). All three curves pass through the same point at the calibration ratio <span class="math inline">\(f \approx 33\%\)</span>. Below 33% staked, the blend-and-offset approach (B) is more generous; above 33%, the offset-only approach (A) is slightly more generous. Both reach zero at 50% staked.
</figcaption>
</figure>
</div>
<p>The crossover at the calibration point is not a coincidence — it is exactly what calibration means. The two curves diverge away from that point in opposite directions:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Staking ratio</th>
<th>Current</th>
<th>Offset-only (A)</th>
<th>Blend+offset (B)</th>
<th>B vs A</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10%</td>
<td>4.8%</td>
<td>9.6%</td>
<td>11.5%</td>
<td>B higher by 20%</td>
</tr>
<tr class="even">
<td>25%</td>
<td>3.0%</td>
<td>4.3%</td>
<td>4.5%</td>
<td>B higher by 6%</td>
</tr>
<tr class="odd">
<td>33%</td>
<td>2.6%</td>
<td>2.6%</td>
<td>2.6%</td>
<td>equal (calibration)</td>
</tr>
<tr class="even">
<td>40%</td>
<td>2.4%</td>
<td>1.5%</td>
<td>1.4%</td>
<td>A higher by 4%</td>
</tr>
<tr class="odd">
<td>45%</td>
<td>2.3%</td>
<td>0.72%</td>
<td>0.68%</td>
<td>A higher by 6%</td>
</tr>
</tbody>
</table>
<p>The differences are largest at low staking. Above the calibration point the two curves are very close, with A retaining a small edge.</p>
<p><strong>Why does A remain slightly more generous above 33%?</strong> The offset in A is proportional to <span class="math inline">\(u\)</span> (linear in staking), but the gross reward decays as <span class="math inline">\(u^{-1/2}\)</span>. Near saturation, the gross decays slower than the offset grows, leaving more net reward per unit than the linear <span class="math inline">\((1-u)\)</span> decay of Approach B. Mathematically, <span class="math inline">\(1 - u^{3/2} &gt; (K_B/K_A)(1-u)\)</span> for <span class="math inline">\(u &gt; u_0\)</span> because the calibration ratio <span class="math inline">\(K_B/K_A = 3/2.195 \approx 1.37\)</span> is not large enough to compensate.</p>
</section>
<section id="total-issuance" class="level2">
<h2 class="anchored" data-anchor-id="total-issuance">Total issuance</h2>
<div id="fig-issuance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-issuance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<style>
  #comparison-issuancecurve-chart { width: 100%; height: 460px; }
</style>

<div id="comparison-issuancecurve-chart"></div>

<script src="issuancecurve.js"></script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-issuance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Annual ETH issuance as a percentage of total supply. The current issuance (blue) rises monotonically. Both proposed curves peak and then return to zero at 50% staked. All three pass through the same issuance at today’s <span class="math inline">\(\sim\!33\%\)</span> staking ratio (<span class="math inline">\(\approx 0.875\%\)</span> of supply), since yields are matched there by calibration. Approach A peaks at <span class="math inline">\(f^* \approx 19.8\%\)</span>, Approach B at <span class="math inline">\(f^* \approx 16.7\%\)</span>.
</figcaption>
</figure>
</div>
<p>The issuance peak <span class="math inline">\(f^*\)</span> determines the boundary of the aggregate anti-discouragement property. For <span class="math inline">\(f &lt; f^*\)</span>, total net issuance grows with staking — a discouragement attack shrinks the reward pool — so the collective deterrent is intact. For <span class="math inline">\(f &gt; f^*\)</span>, the property breaks down.</p>
<p>The difference in peak location follows from the two taper functions. Annual issuance is <span class="math inline">\(I(f) = r(f) \cdot f \cdot S\)</span>, and with <span class="math inline">\(r_{64}(f) \propto u^{-1/2}\)</span> this is proportional to <span class="math inline">\(t(u) \cdot u^{1/2}\)</span> where <span class="math inline">\(t(u)\)</span> is the taper function. Differentiating each and setting to zero:</p>
<p><span class="math display">\[\frac{d}{du}\bigl[(1 - u^{3/2})\,u^{1/2}\bigr] = \frac{1}{2\sqrt{u}} - 2u = 0 \implies u^{3/2} = \tfrac{1}{4} \implies u = 2^{-4/3}, \quad f^*_A = f_\text{sat}\cdot 2^{-4/3} = 2^{-7/3} \approx 19.8\%\]</span></p>
<p><span class="math display">\[\frac{d}{du}\bigl[(1-u)\,u^{1/2}\bigr] = \frac{1-3u}{2\sqrt{u}} = 0 \implies u = \tfrac{1}{3}, \quad f^*_B = f_\text{sat}/3 \approx 16.7\%\]</span></p>
<p>Both lie well below the current <span class="math inline">\(\sim\!33\%\)</span> staking ratio. The anti-discouragement property therefore does not hold at current staking for either proposal — excess staking is already in the region where total issuance falls as staking grows, providing continuous automatic pressure against further staking growth.</p>
</section>
<section id="properties-compared" class="level2">
<h2 class="anchored" data-anchor-id="properties-compared">Properties compared</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th>Offset only (A)</th>
<th>Blend + offset (B)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Net yield formula</td>
<td><span class="math inline">\(K_A(1-u^{3/2})\,r_{64}(f)\)</span></td>
<td><span class="math inline">\(K_B(1-u)\,r_{64}(f)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(K\)</span> / <code>BASE_REWARD_FACTOR</code></td>
<td><span class="math inline">\(\approx 2.195\)</span> / <span class="math inline">\(\approx 140\)</span></td>
<td><span class="math inline">\(3\)</span> / <span class="math inline">\(192\)</span></td>
</tr>
<tr class="odd">
<td>Yield below 33% vs current</td>
<td>Higher, B more so</td>
<td>Higher</td>
</tr>
<tr class="even">
<td>Yield above 33% vs current</td>
<td>Lower, A slightly less so</td>
<td>Lower</td>
</tr>
<tr class="odd">
<td>Issuance peak <span class="math inline">\(f^*\)</span></td>
<td><span class="math inline">\(\approx 19.8\%\)</span></td>
<td><span class="math inline">\(\approx 16.7\%\)</span></td>
</tr>
<tr class="even">
<td>Aggregate anti-discouragement</td>
<td><span class="math inline">\(f &lt; 19.8\%\)</span></td>
<td><span class="math inline">\(f &lt; 16.7\%\)</span></td>
</tr>
<tr class="odd">
<td>Slope of yield at saturation</td>
<td><span class="math inline">\(-6.58\,r_\text{sat}\)</span> per unit <span class="math inline">\(f\)</span></td>
<td><span class="math inline">\(-6.00\,r_\text{sat}\)</span> per unit <span class="math inline">\(f\)</span></td>
</tr>
<tr class="even">
<td><code>get_base_reward_per_increment</code></td>
<td>Unchanged (only <span class="math inline">\(B\)</span> updated)</td>
<td>Modified (linear blend)</td>
</tr>
<tr class="odd">
<td>New offset function needed</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Penalty scaling at 33% staking</td>
<td><span class="math inline">\(\approx 2.20\times\)</span> current</td>
<td><span class="math inline">\(\approx 1.54\times\)</span> current</td>
</tr>
</tbody>
</table>
<section id="slope-at-saturation" class="level3">
<h3 class="anchored" data-anchor-id="slope-at-saturation">Slope at saturation</h3>
<p>Both proposals arrive at zero with a kink — a non-zero slope. Computing at <span class="math inline">\(f = f_\text{sat}\)</span> (<span class="math inline">\(u = 1\)</span>):</p>
<p><span class="math display">\[\left.\frac{dr_A}{df}\right|_{f_\text{sat}} = -\frac{3K_A\,r_\text{sat}}{2f_\text{sat}} \approx -6.58\,r_\text{sat} \approx -14.1\% \text{ per percentage point of staking}\]</span></p>
<p><span class="math display">\[\left.\frac{dr_B}{df}\right|_{f_\text{sat}} = -\frac{K_B\,r_\text{sat}}{f_\text{sat}} = -6\,r_\text{sat} \approx -12.9\% \text{ per percentage point of staking}\]</span></p>
<p>Approach B arrives about 9% more gently than Approach A. The difference traces back to the blend: the modified gross yield in B is already softening toward <span class="math inline">\(r_\text{sat}\)</span> as <span class="math inline">\(f \to f_\text{sat}\)</span>, which partially offsets the steepening due to the offset. In Approach A, the gross reward continues on its <span class="math inline">\(1/\sqrt{f}\)</span> trajectory right up to the saturation point, so the offset must do all the work of bringing the net to zero.</p>
</section>
<section id="penalty-implications" class="level3">
<h3 class="anchored" data-anchor-id="penalty-implications">Penalty implications</h3>
<p>In both proposals, the offset is applied <strong>only to rewards</strong>, not to penalties. Inactivity penalties and slashing are proportional to <code>get_base_reward_per_increment</code>, which is the <em>gross</em> base reward — not the offset-reduced net.</p>
<p><strong>Approach A:</strong> the gross base reward is <span class="math inline">\(K_A \cdot r_{64}(f)\)</span> at all staking ratios, so penalties are a constant <span class="math inline">\(K_A \approx 2.20\times\)</span> current levels regardless of how much ETH is staked.</p>
<p><strong>Approach B:</strong> the gross base reward is the blended value <span class="math inline">\(\tilde{r}(f) = (1-u)\,K_B\,r_{64}(f) + u\,r_\text{sat}\)</span>. Dividing by the current penalty <span class="math inline">\(r_{64}(f)\)</span> gives a multiplier of:</p>
<p><span class="math display">\[\text{B penalty multiplier} = K_B(1-u) + u^{3/2}\]</span></p>
<p>(using <span class="math inline">\(r_\text{sat}/r_{64}(f) = u^{1/2}\)</span>). This starts at <span class="math inline">\(K_B = 3\times\)</span> at zero staking and declines to exactly <span class="math inline">\(1\times\)</span> at saturation, where the blended gross equals <span class="math inline">\(r_\text{sat} = r_{64}(f_\text{sat})\)</span> — the value the current formula gives at 50% staked.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Staking ratio</th>
<th>A penalty multiplier</th>
<th>B penalty multiplier</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10%</td>
<td><span class="math inline">\(\approx 2.20\times\)</span></td>
<td><span class="math inline">\(\approx 2.49\times\)</span></td>
</tr>
<tr class="even">
<td>17% (crossover)</td>
<td><span class="math inline">\(\approx 2.20\times\)</span></td>
<td><span class="math inline">\(\approx 2.20\times\)</span></td>
</tr>
<tr class="odd">
<td>33%</td>
<td><span class="math inline">\(\approx 2.20\times\)</span></td>
<td><span class="math inline">\(\approx 1.54\times\)</span></td>
</tr>
<tr class="even">
<td>40%</td>
<td><span class="math inline">\(\approx 2.20\times\)</span></td>
<td><span class="math inline">\(\approx 1.32\times\)</span></td>
</tr>
<tr class="odd">
<td>50%</td>
<td><span class="math inline">\(\approx 2.20\times\)</span></td>
<td><span class="math inline">\(= 1.00\times\)</span></td>
</tr>
</tbody>
</table>
<p>Below <span class="math inline">\(\sim\!17\%\)</span> staking, B imposes higher penalties than A. Above <span class="math inline">\(\sim\!17\%\)</span> — which includes the current staking ratio and any plausible future level — A imposes higher penalties.</p>
<p>Approach A’s penalty is simple and constant: a fixed <span class="math inline">\(2.2\times\)</span> uplift that is predictable for any validator at any staking level. Approach B’s penalty varies with staking, declining through current levels at <span class="math inline">\(\sim\!33\%\)</span> and fading back to today’s unmodified penalty rate at saturation. Whether a penalty structure that weakens as staking grows toward the cap is desirable is an open design question.</p>
</section>
<section id="spec-architecture" class="level3">
<h3 class="anchored" data-anchor-id="spec-architecture">Spec architecture</h3>
<p>Both proposals require <code>BASE_REWARD_FACTOR</code> to change and both require a new offset function. The single difference is what happens to <code>get_base_reward_per_increment</code>:</p>
<ul>
<li><strong>Approach A</strong>: the function is unchanged in form; only the constant <span class="math inline">\(B\)</span> increases. The same 1/√f formula continues to operate, just calibrated to a higher level.</li>
<li><strong>Approach B</strong>: the function is rewritten to implement the linear blend — it must now look up the saturation balance, compute the deficit, and evaluate the two-term interpolation before returning the blended base reward.</li>
</ul>
<p>The modified <code>get_base_reward_per_increment</code> in Approach B is more complex to audit and verify, since it introduces a conditional structure that Approach A avoids.</p>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>The two proposals are more similar than they might appear: both use a linear offset, both are calibrated to preserve current yields at 33% staking, and both drive net issuance to zero at 50%. But they are not equivalent.</p>
<p><strong>Approach A (offset only)</strong> is the more transparent design. The <span class="math inline">\(1/\sqrt{f}\)</span> formula is untouched; any reader of the spec can see immediately that the base reward mechanism has not changed. The penalty structure is simple and stable: validators always face a constant multiple of today’s penalties. The trade-off is that the offset alone — without any modification of the base reward curve — produces a net yield that arrives at zero with a slightly steeper slope, and retains a slightly higher yield above 33% than Approach B.</p>
<p><strong>Approach B (blend + offset)</strong> modifies the base reward curve to approach a flat level at saturation before the offset brings it to zero. This produces a gentler arrival at zero issuance and a more responsive stabiliser at very low staking (higher yields below 33%). The cost is a more complex <code>get_base_reward_per_increment</code>, and a penalty structure that varies with staking: higher than A at low staking, lower than A above <span class="math inline">\(\sim\!17\%\)</span>, and declining to <span class="math inline">\(1\times\)</span> the current rate at saturation — the same level the unmodified formula would give at 50% staked.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/pintail\.xyz");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="pintail-xyz/pintail-xyz.github.io" data-repo-id="MDEwOlJlcG9zaXRvcnkzMDUwNjk1MTY=" data-category="General" data-category-id="DIC_kwDOEi79zM4C47Ma" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© Pintail</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>