<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-15">
<meta name="description" content="Two alternatives to a linear staking offset — a sine-shaped and an S-curve (sin²) offset — calibrated to match current issuance at 33% staked, with gentler behaviour near the saturation point and stronger tapering in between.">

<title>Smooth Issuance Tapering: Sine and S-Curve Offsets for Ethereum – pintail’s notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-2cb179d66e5887d6bd257c4a22d491ba.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script data-goatcounter="https://pintail.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<meta name="quarto:status" content="draft">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Smooth Issuance Tapering: Sine and S-Curve Offsets for Ethereum – pintail’s notes">
<meta property="og:description" content="Two alternatives to a linear staking offset — a sine-shaped and an S-curve (sin²) offset — calibrated to match current issuance at 33% staked, with gentler behaviour near the saturation point and stronger tapering in between.">
<meta property="og:site_name" content="pintail's notes">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><div id="quarto-draft-alert" class="alert alert-warning"><i class="bi bi-pencil-square"></i>Draft</div>
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../assets/pintail_silhouette.svg" alt="Pintail duck silhouette" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">pintail’s notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/pintail_xyz"> <i class="bi bi-twitter" role="img" aria-label="Twitter">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/pintail-xyz"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tldr" id="toc-tldr" class="nav-link active" data-scroll-target="#tldr">tl;dr</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#calibration" id="toc-calibration" class="nav-link" data-scroll-target="#calibration">Calibration</a></li>
  <li><a href="#properties" id="toc-properties" class="nav-link" data-scroll-target="#properties">Properties</a>
  <ul class="collapse">
  <li><a href="#yield" id="toc-yield" class="nav-link" data-scroll-target="#yield">Yield</a></li>
  <li><a href="#slope-at-saturation" id="toc-slope-at-saturation" class="nav-link" data-scroll-target="#slope-at-saturation">Slope at saturation</a></li>
  <li><a href="#total-issuance" id="toc-total-issuance" class="nav-link" data-scroll-target="#total-issuance">Total Issuance</a></li>
  <li><a href="#anti-discouragement" id="toc-anti-discouragement" class="nav-link" data-scroll-target="#anti-discouragement">Anti-Discouragement</a></li>
  </ul></li>
  <li><a href="#spec-considerations" id="toc-spec-considerations" class="nav-link" data-scroll-target="#spec-considerations">Spec Considerations</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Smooth Issuance Tapering: Sine and S-Curve Offsets for Ethereum</h1>
</div>

<div>
  <div class="description">
    Two alternatives to a linear staking offset — a sine-shaped and an S-curve (sin²) offset — calibrated to match current issuance at 33% staked, with gentler behaviour near the saturation point and stronger tapering in between.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>[Intro — reference to the linear tapering post; motivation for exploring alternative offset shapes; note that this post focuses purely on shape differences by anchoring all three curves to the same point at today’s staking ratio.]</p>
<section id="tldr" class="level2">
<h2 class="anchored" data-anchor-id="tldr">tl;dr</h2>
<ul>
<li>The <a href="../linear-issuance-tapering/">linear staking offset</a> is a clean, implementable design, but its offset grows at a constant rate and its net yield has a non-zero slope right up to the saturation point — a sharp final approach to zero.</li>
<li>Two alternative offset shapes — <strong>sine</strong> (<span class="math inline">\(\sin\frac{\pi f}{2f_\text{sat}}\)</span>) and <strong>S-curve</strong> (<span class="math inline">\(\sin^2\frac{\pi f}{2f_\text{sat}}\)</span>) — each have zero slope at <span class="math inline">\(f_\text{sat}\)</span>, giving a softer final approach, but require a larger gross reward factor (<code>BASE_REWARD_FACTOR</code>) to compensate. Both shapes are applied only over <span class="math inline">\([0, f_\text{sat}]\)</span>; above 50% the offset equals the full base reward and net yield is zero. (A naive extension of the sine shape beyond <span class="math inline">\(f_\text{sat}\)</span> would cause its offset to decrease and net yield to re-emerge around <span class="math inline">\(f \approx 67\%\)</span>; the clamping prevents this.)</li>
<li>Calibrating all three curves to match current issuance at <span class="math inline">\(f \approx 33\%\)</span> reveals the shape differences cleanly: below 33% all three offer higher yields than today; above 33% sine and S-curve are more aggressive than linear; and all three reach zero at 50%.</li>
<li>Near saturation, sine has roughly half the slope of linear, and S-curve roughly 40% — both produce a materially softer landing.</li>
<li>The calibrated <code>BASE_REWARD_FACTOR</code> values are approximately 140, 165, and 219 for the linear, S-curve, and sine proposals respectively — none of them round numbers.</li>
<li>The sine curve’s calibration has an exact closed form: <span class="math inline">\(K_\text{sine} = 2 + \sqrt{2}\)</span>, because <span class="math inline">\(\sin(\pi/3)\cdot\sqrt{2/3} = 1/\sqrt{2}\)</span> exactly.</li>
</ul>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>All three proposals share the same structural form. Let <span class="math inline">\(r(f) = B \cdot E / \sqrt{f \cdot S \cdot 10^9}\)</span> denote the gross nominal yield computed with <code>BASE_REWARD_FACTOR</code> <span class="math inline">\(= B\)</span>, let <span class="math inline">\(r_\text{sat} = r(f_\text{sat})\)</span>, and let <span class="math inline">\(\phi(u) \in [0,1]\)</span> be the <strong>offset shape function</strong> for <span class="math inline">\(u = f/f_\text{sat} \in [0,1]\)</span>. Net yield under each proposal is:</p>
<p><span class="math display">\[r_\text{new}(f) = \begin{cases} K\,\bigl[r_\text{64}(f) - \phi(f/f_\text{sat})\cdot r_\text{64}(f_\text{sat})\bigr] &amp; f \le f_\text{sat} \\ 0 &amp; f &gt; f_\text{sat} \end{cases}\]</span></p>
<p>where <span class="math inline">\(r_\text{64}\)</span> denotes the yield computed with the current <code>BASE_REWARD_FACTOR</code> <span class="math inline">\(= 64\)</span>, and <span class="math inline">\(K = B/64\)</span> is the gross reward multiplier. Above <span class="math inline">\(f_\text{sat}\)</span> the offset equals the full gross base reward and net yield is zero.</p>
<p>The three offset shapes, defined on <span class="math inline">\([0, f_\text{sat}]\)</span>, are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variant</th>
<th><span class="math inline">\(\phi(u)\)</span>, <span class="math inline">\(u = f/f_\text{sat} \in [0,1]\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linear</td>
<td><span class="math inline">\(u\)</span></td>
</tr>
<tr class="even">
<td>Sine</td>
<td><span class="math inline">\(\sin(\pi u/2)\)</span></td>
</tr>
<tr class="odd">
<td>S-curve</td>
<td><span class="math inline">\(\sin^2(\pi u/2) = \tfrac{1-\cos(\pi u)}{2}\)</span></td>
</tr>
</tbody>
</table>
<p>All three satisfy <span class="math inline">\(\phi(0) = 0\)</span> and <span class="math inline">\(\phi(1) = 1\)</span>, so net issuance reaches zero at <span class="math inline">\(f = f_\text{sat} = 50\%\)</span>.</p>
<p><strong>Why the explicit <span class="math inline">\(f &gt; f_\text{sat}\)</span> floor is needed for sine and S-curve.</strong> The linear offset <span class="math inline">\(\phi(u) = u\)</span> grows without bound past <span class="math inline">\(u = 1\)</span>, so it always exceeds the base reward above <span class="math inline">\(f_\text{sat}\)</span> and the <span class="math inline">\(\max(0,\ldots)\)</span> floor suffices. The sine and S-curve shapes behave differently: <span class="math inline">\(\sin(\pi u/2)\)</span> peaks at <span class="math inline">\(u=1\)</span> and then <em>decreases</em> (entering the descending half of the cycle), falling to zero at <span class="math inline">\(u=2\)</span>. Without the explicit floor, the offset would eventually drop back below the base reward — around <span class="math inline">\(f \approx 67\%\)</span> for the sine curve — causing net yield to turn positive again above saturation. Applying the shape only on <span class="math inline">\([0, f_\text{sat}]\)</span> and holding the offset at the full base reward above that point eliminates this pathology.</p>
<div id="fig-offset" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-offset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<style>
  #sine-offsetcurve-chart { width: 100%; height: 420px; }
</style>

<div id="sine-offsetcurve-chart"></div>

<script src="offsetcurve.js"></script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-offset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The three offset shapes <span class="math inline">\(\phi(u)\)</span> as a fraction of the base reward at saturation. The transition is applied only over <span class="math inline">\([0, 50\%]\)</span>; above the saturation point (shaded region) all three curves hold the offset at 100% of the base reward, giving zero net yield. The sine curve is convex throughout <span class="math inline">\([0, f_\text{sat}]\)</span> and lies above the linear line everywhere. The S-curve (sin²) is S-shaped: it lies below linear for <span class="math inline">\(f &lt; 25\%\)</span>, crosses it at <span class="math inline">\(f = 25\%\)</span>, and lies above for <span class="math inline">\(25\% &lt; f \le 50\%\)</span>. Both sine and S-curve have zero slope at <span class="math inline">\(u = 1\)</span>; the S-curve also has zero slope at <span class="math inline">\(u = 0\)</span>.
</figcaption>
</figure>
</div>
</section>
<section id="calibration" class="level2">
<h2 class="anchored" data-anchor-id="calibration">Calibration</h2>
<p>To isolate the effect of shape from the effect of level, we calibrate <span class="math inline">\(K\)</span> for each variant so that the net yield at the current staking ratio <span class="math inline">\(f_0 = \tfrac{1}{3}\)</span> equals today’s yield:</p>
<p><span class="math display">\[K \cdot \Bigl[r_\text{64}(f_0) - \phi\!\bigl(f_0/f_\text{sat}\bigr)\cdot r_\text{64}(f_\text{sat})\Bigr] = r_\text{64}(f_0)\]</span></p>
<p>Since <span class="math inline">\(r_\text{64}(f_\text{sat})/r_\text{64}(f_0) = \sqrt{f_0/f_\text{sat}} = \sqrt{2/3}\)</span> and <span class="math inline">\(f_0/f_\text{sat} = \tfrac{2}{3}\)</span>:</p>
<p><span class="math display">\[K = \frac{1}{1 - \phi(2/3)\cdot\sqrt{2/3}}\]</span></p>
<p>The three calibrated values are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Variant</th>
<th><span class="math inline">\(\phi(2/3)\)</span></th>
<th><span class="math inline">\(\phi(2/3)\cdot\sqrt{2/3}\)</span></th>
<th><span class="math inline">\(K\)</span></th>
<th><span class="math inline">\(B = 64K\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linear</td>
<td><span class="math inline">\(2/3\)</span></td>
<td><span class="math inline">\(2\sqrt{6}/9 \approx 0.544\)</span></td>
<td><span class="math inline">\(\approx 2.195\)</span></td>
<td><span class="math inline">\(\approx 140\)</span></td>
</tr>
<tr class="even">
<td>S-curve</td>
<td><span class="math inline">\(3/4\)</span></td>
<td><span class="math inline">\(\sqrt{6}/4 \approx 0.612\)</span></td>
<td><span class="math inline">\(4/(4-\sqrt{6}) \approx 2.580\)</span></td>
<td><span class="math inline">\(\approx 165\)</span></td>
</tr>
<tr class="odd">
<td>Sine</td>
<td><span class="math inline">\(\sqrt{3}/2\)</span></td>
<td><span class="math inline">\(1/\sqrt{2}\)</span></td>
<td><span class="math inline">\(2 + \sqrt{2} \approx 3.414\)</span></td>
<td><span class="math inline">\(\approx 219\)</span></td>
</tr>
</tbody>
</table>
<p>The sine calibration is exact: <span class="math inline">\(\sin(\pi/3)\cdot\sqrt{2/3} = \frac{\sqrt{3}}{2}\cdot\frac{\sqrt{2}}{\sqrt{3}} = \frac{1}{\sqrt{2}}\)</span>, which gives <span class="math inline">\(K_\text{sine} = 1/(1-1/\sqrt{2}) = 2+\sqrt{2}\)</span>.</p>
<p>None of the three values of <span class="math inline">\(B\)</span> are round integers, which is worth noting for spec purposes — see the <a href="#spec-considerations">discussion below</a>.</p>
</section>
<section id="properties" class="level2">
<h2 class="anchored" data-anchor-id="properties">Properties</h2>
<section id="yield" class="level3">
<h3 class="anchored" data-anchor-id="yield">Yield</h3>
<div id="fig-yield" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yield-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<style>
  #sine-yieldcurve-chart { width: 100%; height: 460px; }
</style>

<div id="sine-yieldcurve-chart"></div>

<script src="yieldcurve.js"></script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yield-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Consensus-layer nominal yield as a function of staking ratio. All three proposed curves pass through the same point as the current curve at <span class="math inline">\(f = 33\%\)</span>. Below that, all three are above the current curve — offering stronger staking incentives when participation is low. Above 33%, sine and S-curve taper more aggressively than the linear variant. All three reach zero at 50%.
</figcaption>
</figure>
</div>
<p>The curves separate into two distinct regimes once calibrated at 33%:</p>
<p><strong>Below 33%</strong> — all three proposed curves lie above today’s yield. The sine curve is most generous at low staking (because its large K = 2+√2 amplifies the gross reward), providing roughly five times today’s yield at 10% staking. The S-curve and linear variants are intermediate. This is a natural stabiliser: if staking falls, the yield rise is larger under each proposed curve than under the current one, attracting validators back more strongly.</p>
<p><strong>Above 33%</strong> — the sine and S-curve taper faster than the linear variant. At 40% staking, the linear variant offers about 57% of today’s yield, while the sine and S-curve are closer to 46–47%. By 45%, the linear variant is at 28% of today’s yield versus about 17–19% for the others. The sine and S-curve therefore provide a stronger market signal against excess staking throughout the danger zone.</p>
</section>
<section id="slope-at-saturation" class="level3">
<h3 class="anchored" data-anchor-id="slope-at-saturation">Slope at saturation</h3>
<p>The most important qualitative difference between the variants is the slope of the net yield as <span class="math inline">\(f \to f_\text{sat}\)</span>. Since <span class="math inline">\(\phi'(1) = 0\)</span> for both the sine and S-curve (the offset is flat at saturation), the slope of the net yield is:</p>
<p><span class="math display">\[\left.\frac{dr_\text{new}}{df}\right|_{f=f_\text{sat}} = \begin{cases}
-3K\,r_\text{sat}/f_\text{sat} &amp; \text{linear}\\
-K\,r_\text{sat}/f_\text{sat} &amp; \text{sine or S-curve}
\end{cases}\]</span></p>
<p>With the calibrated K values:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variant</th>
<th>Slope magnitude at <span class="math inline">\(f_\text{sat}\)</span></th>
<th>Relative to linear</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linear</td>
<td><span class="math inline">\(\propto 3 \times 2.195 = 6.58\)</span></td>
<td>1.00</td>
</tr>
<tr class="even">
<td>Sine</td>
<td><span class="math inline">\(\propto 1 \times 3.414 = 3.41\)</span></td>
<td>0.52</td>
</tr>
<tr class="odd">
<td>S-curve</td>
<td><span class="math inline">\(\propto 1 \times 2.580 = 2.58\)</span></td>
<td>0.39</td>
</tr>
</tbody>
</table>
<p>The sine curve approaches zero with about half the slope of the linear version. The S-curve approaches with about 40% of the linear slope — the softest landing of the three. Validators at 48–49% staking face a more gradual final reduction; there is no abrupt cliff.</p>
</section>
<section id="total-issuance" class="level3">
<h3 class="anchored" data-anchor-id="total-issuance">Total Issuance</h3>
<div id="fig-issuance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-issuance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<style>
  #sine-issuancecurve-chart { width: 100%; height: 460px; }
</style>

<div id="sine-issuancecurve-chart"></div>

<script src="issuancecurve.js"></script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-issuance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Annual ETH issuance as a percentage of total supply. All three proposed curves equal the current issuance at <span class="math inline">\(f = 33\%\)</span> and fall to zero at <span class="math inline">\(f = 50\%\)</span>. The proposed curves each peak at a lower staking ratio than the current curve: approximately <span class="math inline">\(19.8\%\)</span> for the linear variant, <span class="math inline">\(18\%\)</span> for the S-curve, and <span class="math inline">\(15.5\%\)</span> for the sine.
</figcaption>
</figure>
</div>
<p>The calibration anchors all three curves to the current issuance at 33%. Below 33%, the sine and S-curve rise higher than the linear variant because their larger <span class="math inline">\(K\)</span> amplifies the gross reward more; above 33%, they taper more steeply to zero.</p>
</section>
<section id="anti-discouragement" class="level3">
<h3 class="anchored" data-anchor-id="anti-discouragement">Anti-Discouragement</h3>
<p>Total issuance is increasing in <span class="math inline">\(f\)</span> for <span class="math inline">\(f &lt; f^*\)</span> and decreasing thereafter. The peak <span class="math inline">\(f^*\)</span> depends only on the shape <span class="math inline">\(\phi\)</span>, not on <span class="math inline">\(K\)</span>, and is the same under calibrated or uncalibrated variants:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variant</th>
<th><span class="math inline">\(f^*\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linear</td>
<td><span class="math inline">\(\approx 19.8\%\)</span></td>
</tr>
<tr class="even">
<td>S-curve</td>
<td><span class="math inline">\(\approx 18\%\)</span></td>
</tr>
<tr class="odd">
<td>Sine</td>
<td><span class="math inline">\(\approx 15.5\%\)</span></td>
</tr>
</tbody>
</table>
<p>All three lie well below the current <span class="math inline">\(\sim\!33\%\)</span> staking ratio, so the anti-discouragement property is preserved in all cases.</p>
</section>
</section>
<section id="spec-considerations" class="level2">
<h2 class="anchored" data-anchor-id="spec-considerations">Spec Considerations</h2>
<p>The sine and S-curve shapes cannot be computed exactly in integer arithmetic. A rational approximation or lookup table would be required in the consensus-layer spec.</p>
<p>The calibrated <code>BASE_REWARD_FACTOR</code> values (<span class="math inline">\(\approx 140\)</span>, <span class="math inline">\(165\)</span>, <span class="math inline">\(219\)</span>) are not round numbers. In practice, the spec would round to the nearest integer, introducing a small (<span class="math inline">\(&lt; 0.5\%\)</span>) discrepancy at the 33% calibration point.</p>
<p>For comparison: the original linear proposal used <code>BASE_REWARD_FACTOR</code> <span class="math inline">\(= 128\)</span> (<span class="math inline">\(K = 2\)</span>) as a convenient round value, accepting an <span class="math inline">\(\sim\!9\%\)</span> yield reduction at deployment rather than an exact match. An analogous choice for the sine proposal would be, say, <span class="math inline">\(B = 218\)</span>, accepting a similarly small deviation at 33%.</p>
<p>The penalty for non-participation scales with <span class="math inline">\(B\)</span>, so the larger values required by sine and S-curve also increase slashing and inactivity penalties — by a factor of <span class="math inline">\(3.4\times\)</span> for sine vs.&nbsp;<span class="math inline">\(2.2\times\)</span> for linear relative to today. This is a governance consideration independent of the yield question.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>[Summary of tradeoffs; which variant to recommend; comparison with other proposals; path to an EIP.]</p>
<p>With the yield level anchored at 33%, the three curves differ in only two ways:</p>
<ol type="1">
<li><p><strong>Below 33%</strong>: how generously they reward stakers when participation is low. Sine offers the most headroom; linear the least. All are above the current curve.</p></li>
<li><p><strong>Above 33%</strong>: how aggressively they push back against excess staking, and how smoothly they approach zero. Sine and S-curve are steeper in the 33–45% range; all three are gentler at the very end, with S-curve gentlest.</p></li>
</ol>
<p>If the goal is a strong automatic stabiliser — a curve that reacts sharply to staking above 33% while providing a soft landing at saturation — the S-curve has the better-motivated shape. Its sin² form is the <a href="https://en.wikipedia.org/wiki/Raised_cosine_distribution">raised cosine</a> from signal processing: zero slope at both ends by design, maximum responsiveness in the middle. It is more aggressive than linear in the danger zone (above 25%) and gentler near saturation.</p>
<p>The linear offset remains the most practically deployable: its <code>BASE_REWARD_FACTOR</code> of 128 is a clean integer, and it reduces to a single multiply-and-divide in the spec. Whether the soft landing and stronger corrective properties of sine or S-curve justify the added implementation complexity and larger gross reward factor is a question for the community.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/pintail\.xyz");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="pintail-xyz/pintail-xyz.github.io" data-repo-id="MDEwOlJlcG9zaXRvcnkzMDUwNjk1MTY=" data-category="General" data-category-id="DIC_kwDOEi79zM4C47Ma" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© Pintail</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>